services:
  - type: web
    name: angular-todo-app
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run serve:ssr:project
    publishPath: dist/project/browser
    rootDir: ./
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_URL
        value: https://jsonplaceholder.typicode.com
